import type { Metadata } from "next";
import { Playfair_Display, Roboto, Rye } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const customFont = Rye({
  variable: '--font-custom',
  subsets: ["latin", "latin-ext"],
  weight: ["400"],
  style: "normal",
  display: "auto"
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700"],
});


export const metadata: Metadata = {
  title: "Stewart Boots",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${customFont.variable} ${roboto.variable} antialiased min-h-screen flex flex-col`}
      >
        <Header />
        <main
          className="mt-14 md:mt-24"
        >
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
